version: "3"

services:
    # Database
    db:
        image: mariadb:10.6.4-focal
        command: "--default-authentication-plugin=mysql_native_password"
        volumes:
        - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        expose:
        - 3306
        - 33060
        networks:
        - wpsite
    # phpmyadmin
    phpmyadmin:
        depends_on:
        - db
        image: phpmyadmin:latest
        restart: always
        ports:
        - "8008:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        networks:
        - wpsite
    # Wordpress
    wordpress:
        depends_on:
        - db
        image: wordpress:latest
        ports:
        - "80:80"
        restart: always
        volumes: ["./wordpress:/var/www/html"]
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        networks:
        - wpsite
networks:
    wpsite:
volumes:
    db_data: